//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicao
    {
        public int Id { get; set; }
        public string Funcao { get; set; }
        public string Descrição { get; set; }
    
        public virtual Jogador Jogador { get; set; }
    }
}
